{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Accuracy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hit_rate, mrr FROM accuracy "
    }
   ]
  },
  {
   "title": "Knowledge base",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM knownledge " }
   ]
  },
  {
   "title": "Distribution of years",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT CAST(year AS INT) AS year_int FROM knownledge;"
    }
   ]
  },
  {
   "title": "Ground Truth",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM ground_truth " }
   ]
  }
 ]
}